appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: vswe5VMRtaZe+SnkicEK9xPdceWiiYET6KZEZbInewrdK1hJBZwZJQNyHImwD+DoCMLPbk6ujYxTfxhdvgyajxu8nzouRJy7Cr0ZG6DcyCpEo5cLTmyoU5BmYVFnYGTNhfeiWdJBrzWZQWkwF9qauY3LvwM/xjpMPLc0mYRjLq8/xXPT47mUHOF7DqztGOhbRd/JAGgyADwfR7QceLzn/GVoAvn6q+JRmFnqNDtALsa+w4IkrDDIhCjVVs+Yz59W+1NufceT2+1ZqPrEmK8J36zoCKW60K5dM8xdDA0pChGD/CUAVYQo3IwHAyGWqqNNAzoKsSTsXC6NCbEWBu70TYEK+bCdjjUNtnVKg3uNCAsJ8tkZ7TKBK4iuLcRZHSFXZW082H0vRJ6d9slGHN/zj7+uvDnGQVYVJTZ14c1wgsjEvctw4yz5HPsBvfKBAJzKkpQ1WDXsCeL8yvqujGLpjCH7RKlaKr+bBe3ru0Of/DU0Ku/2xVCl+GsfBtuJWX4pxoMfrcuvj1AJUFKpHObhxzjB/DGB6cfzeW+GwDZck5EcRZcrAYtpNtPqHmudSKHIjGfl6R0fRjNq2Qu9VZqQ7D6L7GrtTNw0e14suqahzBY0RMVrOWb+p5o8XtTN/9yFKodvjmvBBeP+Bq0vtKNSHFUr8j0hqYmcs+8ocEw44ek=}
